//ListItems
export const RESET = "APP_RESET";
export const ITEMS_LIST_FULFILLED = "ITEMS_LIST_FULFILLED";
export const ITEMS_LIST_REJECTED = "ITEMS_LIST_REJECTED";
export const ITEMS_LIST_PENDING = "ITEMS_LIST_PENDING";
